### ISSUE TITLE
Migrate on js-debug extension's debugging core

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-cordova#613]
We are planning to migrate Cordova extension debugging core to [js-debug](https://github.com/microsoft/vscode-js-debug) extension one, since currently used [vscode-chrome-debug-core](https://github.com/microsoft/vscode-chrome-debug-core) tool will be deprecated soon. For providing communication between app and `js-debug` extension the special [CDP proxy](https://github.com/microsoft/vscode-cdp-proxy) will be used. It will allow to adapt platform specific features on the debugging protocol level.

Below there is the migration roadmap for tracking the progress.

# Roadmap

- [x] **[proxy]** Implement translation of a target URL to Websocket inspector URL
- [x] **[extension]** Implement Debug Configuration Provider
- [x] **[extension]** Implement running of the debug adapter directly inside the extension and make VS Code to connect to it instead of launching a new external debug adapter per session
- [x] **[extension]** Implement launch of CDP proxy
- [x] **[extension]** Implement starting of js-debug extension's debug session
- [x] **[extension]** Implement multiroot workspaces support
- [x] **[proxy]** Add listeners on CDP events inside the proxy
- [x] **[proxy]** Implement correct path resolving 
- [x] **[extension]** Adapt current implementation of pre-attach setup for Android emulators and devices to proxy approach
- [x] **[extension]** Adapt current implementation of pre-attach setup for iOS simulator to proxy approach 
- [x] **[proxy]** Implement translation of flat session methods to non-flat ones if it's possible (to provide communication with IWDP)
- [x] **[ios-debug]** Investigate possible solutions for #564 (example https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/pull/177)
- [x] **[extension]** Adapt current implementation of Ionic live-reload handling to proxy approach
- [x] **[extension]** Сover changes with tests
- [x] **[extension]** Test the updated extension to make sure that all debug arguments work well
- [x] **[extension]** Migrate from TSLint to ESLint

**Comment by SounD120** [comment]
Cordova Tools v2.0.0 with js-debug debugger have been released just now.
